"""Python client for the Arker VM API."""
from .computer import (
    Arker,
    ArkerError,
    BackgroundRunResult,
    CancelRunResponse,
    CompletedRunResult,
    Computer,
    DeleteFilesystemResponse,
    DeleteVmResponse,
    Filesystem,
    Filesystems,
    ForkVmResponse,
    ListFilesystemsResponse,
    ListRunsResponse,
    ListVmsResponse,
    RetryOptions,
    Run,
    RunResult,
    RunSummary,
    Session,
    Sync,
    SyncCreateResponse,
    Vm,
    VmList,
    VmSummary,
    # Backwards-compat re-exports of the pre-rename type names. Drop
    # in a future major release once downstream users migrate to the
    # bare entity names (Vm / Session / Run).
    RunStatusResponse,
    SessionInfo,
    VmInfo,
)

__all__ = [
    "Arker",
    "ArkerError",
    "BackgroundRunResult",
    "CancelRunResponse",
    "CompletedRunResult",
    "Computer",
    "DeleteFilesystemResponse",
    "DeleteVmResponse",
    "Filesystem",
    "Filesystems",
    "ForkVmResponse",
    "ListFilesystemsResponse",
    "ListRunsResponse",
    "ListVmsResponse",
    "RetryOptions",
    "Run",
    "RunResult",
    "RunStatusResponse",
    "RunSummary",
    "Session",
    "SessionInfo",
    "Sync",
    "SyncCreateResponse",
    "Vm",
    "VmInfo",
    "VmList",
    "VmSummary",
]
__version__ = "0.3.0"
